#!/usr/bin/env python3
"""Generate THIRD-PARTY-LICENSES.txt from the Rust dependency graph.

The output has three sections:

    1. Rust crates statically linked into onykia_engine.wasm — one block
       per SPDX license id, listing every crate that uses it (with each
       crate's Cargo.toml `authors` preserved as a copyright line) and
       the canonical license body once.
    2. Bundled fonts — the upstream typst-assets NOTICE reproduced
       verbatim from the resolved crate source. Tracks the pinned
       version automatically.
    3. Typst-internal upstream attributions — the static fragment in
       scripts/license-appendix.txt (LLVM Exception, LPPL summary,
       NCSA). NOTICE describes which file each section applies to.

Inputs:
    - cargo-about JSON on stdin (run with `--format=json`).
    - `cargo metadata` for resolving the typst-assets manifest path.

The generator is deterministic: same Cargo.lock + same fragment yields
the same output, so CI can verify freshness with a plain diff.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
APPENDIX_PATH = REPO_ROOT / "scripts" / "license-appendix.txt"
RUST_MANIFEST = REPO_ROOT / "src" / "rust" / "Cargo.toml"

HEADER = """\
==========================================================================
onykia-engine — Third-Party License Texts
==========================================================================

This file collects every license text required by software bundled into
onykia-engine's distributed artefacts: the npm packages
@mudomi/onykia-engine, @mudomi/onykia-codemirror, @mudomi/onykia-monaco,
and the compiled WebAssembly module onykia_engine.wasm.

NOTICE explains which upstream attributions each section satisfies and
why each license appears here. NOTICE and this file ship together; any
redistribution of an onykia-engine artefact must include both.

This file is auto-generated by scripts/update-licenses.sh. Do not
hand-edit. Sources: cargo-about (Rust crate licenses), the upstream
typst-assets NOTICE (bundled fonts), and scripts/license-appendix.txt
(Typst-internal upstream attributions).
"""

SECTION_RULE = "-" * 74
DOUBLE_RULE = "=" * 74

# Some SPDX licenses (MIT, BSD-*, Zlib, ISC, BSL-1.0) embed the
# copyright line of the *specific crate* whose LICENSE file
# cargo-about happened to read. Reproducing that line as if it
# governs the whole SPDX group misattributes copyright. For those
# licenses we extract the canonical license body at a known anchor
# phrase and prepend a placeholder pointing the reader to the
# per-crate copyright list above. Apache-2.0, CC0-1.0 and Unicode-3.0
# carry no such crate-specific copyright header (or, in Unicode's
# case, the canonical Unicode Inc. copyright that must be preserved
# verbatim) and are passed through.

CANONICAL_BODY_ANCHOR: dict[str, str] = {
    "MIT": "Permission is hereby granted, free of charge",
    "BSD-2-Clause": "Redistribution and use in source and binary forms",
    "BSD-3-Clause": "Redistribution and use in source and binary forms",
    "Zlib": "This software is provided",
    "ISC": "Permission to use, copy, modify",
    "BSL-1.0": "Permission is hereby granted, free of charge,",
}

CANONICAL_TITLE: dict[str, str] = {
    "MIT": "MIT License",
    "BSD-2-Clause": 'BSD 2-Clause "Simplified" License',
    "BSD-3-Clause": 'BSD 3-Clause "New" or "Revised" License',
    "Zlib": "zlib License",
    "ISC": "ISC License",
    "BSL-1.0": "Boost Software License 1.0",
}

CANONICAL_PLACEHOLDER = (
    "Copyright (c) [see the per-crate copyright notices listed above for the\n"
    "crates distributed under this license]."
)


def normalize_license_text(spdx: str, text: str) -> str:
    """Return a canonical license body for `spdx`, with crate-specific
    copyright headers replaced by a cross-reference placeholder."""
    anchor = CANONICAL_BODY_ANCHOR.get(spdx)
    if anchor is None:
        return text.rstrip()
    idx = text.find(anchor)
    if idx == -1:
        # cargo-about gave us text we don't recognise; fail loudly so
        # we notice rather than silently shipping a misattributed body.
        raise RuntimeError(
            f"Cannot locate canonical body anchor {anchor!r} in {spdx} text"
        )
    body = text[idx:].rstrip()
    title = CANONICAL_TITLE.get(spdx, "")
    head = f"{title}\n\n" if title else ""
    return f"{head}{CANONICAL_PLACEHOLDER}\n\n{body}"


def cargo_metadata() -> dict[str, Any]:
    out = subprocess.run(
        ["cargo", "metadata", "--format-version=1", "--manifest-path", str(RUST_MANIFEST)],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(out.stdout)


def crate_root(metadata: dict[str, Any], name: str) -> Path:
    for pkg in metadata["packages"]:
        if pkg["name"] == name:
            return Path(pkg["manifest_path"]).parent
    raise RuntimeError(f"Crate {name!r} not in cargo metadata; is it still a dependency?")


def render_section_crates(about: dict[str, Any]) -> str:
    licenses = about["licenses"]

    # Group crates by SPDX id; pick the first encountered text body as
    # canonical. cargo-about's `licenses` array can have multiple entries
    # per id when crates ship slightly different texts (e.g. trailing
    # whitespace), but the SPDX text is the legally relevant one.
    by_id: dict[str, dict[str, Any]] = {}
    for entry in licenses:
        spdx = entry["id"]
        bucket = by_id.setdefault(
            spdx, {"name": entry["name"], "text": entry["text"], "crates": set()}
        )
        for used in entry.get("used_by", []):
            crate = used["crate"]
            authors = tuple(crate.get("authors") or ())
            bucket["crates"].add((crate["name"], crate["version"], authors))

    parts: list[str] = []
    parts.append(DOUBLE_RULE)
    parts.append("Section 1 — Rust crates statically linked into onykia_engine.wasm")
    parts.append(DOUBLE_RULE)
    parts.append("")
    parts.append(
        "Each subsection lists every crate using the named license, with the\n"
        "crate's own Cargo.toml authors preserved as a copyright line, followed\n"
        "by the canonical license text reproduced once."
    )

    for spdx in sorted(by_id):
        bucket = by_id[spdx]
        parts.append("")
        parts.append(SECTION_RULE)
        parts.append(f"{bucket['name']} ({spdx})")
        parts.append(SECTION_RULE)
        parts.append("")
        parts.append("Used by:")
        for cname, cversion, authors in sorted(bucket["crates"]):
            parts.append(f"  * {cname} {cversion}")
            for author in authors:
                parts.append(f"      Copyright (c) {author}")
        parts.append("")
        parts.append(normalize_license_text(spdx, bucket["text"]))

    return "\n".join(parts) + "\n"


def render_section_fonts(metadata: dict[str, Any]) -> str:
    root = crate_root(metadata, "typst-assets")
    notice_path = root / "NOTICE"
    if not notice_path.is_file():
        raise RuntimeError(f"typst-assets NOTICE not found at {notice_path}")

    parts: list[str] = []
    parts.append(DOUBLE_RULE)
    parts.append("Section 2 — Bundled fonts (typst-assets)")
    parts.append(DOUBLE_RULE)
    parts.append("")
    parts.append(
        "onykia_engine.wasm embeds the default font set from typst-assets via\n"
        "its `fonts` feature (see src/rust/src/world.rs). The block below is\n"
        "reproduced verbatim from the upstream typst-assets NOTICE at the\n"
        "version pinned in Cargo.lock."
    )
    parts.append("")
    parts.append(notice_path.read_text(encoding="utf-8").rstrip())
    return "\n".join(parts) + "\n"


def render_section_appendix() -> str:
    if not APPENDIX_PATH.is_file():
        raise RuntimeError(f"License appendix not found at {APPENDIX_PATH}")

    parts: list[str] = []
    parts.append(DOUBLE_RULE)
    parts.append("Section 3 — Typst-internal upstream attributions")
    parts.append(DOUBLE_RULE)
    parts.append("")
    parts.append(
        "These license texts apply to portions of code or content vendored\n"
        "inside the Typst crates (typst, typst-syntax, typst-render,\n"
        "typst-utils, typst-library). NOTICE §1 describes which file each\n"
        "section applies to."
    )
    parts.append("")
    parts.append(APPENDIX_PATH.read_text(encoding="utf-8").rstrip())
    return "\n".join(parts) + "\n"


def main() -> int:
    about = json.load(sys.stdin)
    metadata = cargo_metadata()

    out: list[str] = [HEADER]
    out.append(render_section_crates(about))
    out.append(render_section_fonts(metadata))
    out.append(render_section_appendix())
    out.append(DOUBLE_RULE)
    out.append("End of THIRD-PARTY-LICENSES.txt")
    out.append(DOUBLE_RULE)

    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
